mysite/dl_images/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    # path('/hello',views.hello,name='hello')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('dl_images/',include('dl_images.urls')),
    # path('',views.index,name='index'),
    path('admin/', admin.site.urls),
]
print("e")

mysite/dl_images/models.py
from django.db import models

# Create your models here.

    

mysite/dl_images/forms.py
from email import message
from socket import fromshare
from unicodedata import name
from unittest.util import _MAX_LENGTH
from django import forms

class search_form(forms.Form):
    url = forms.CharField(max_length=150)
    # message = forms.CharField(widget=forms.Textarea,max_length=100)

mysite/dl_images/views.py
# from http.client import HTTPResponse
from email import message
from importlib.resources import contents
from re import template
import re
from time import sleep
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from dl_images.forms import search_form
from django.views import View
from dl_images.soup import dl
from django.http import JsonResponse

process = 0
total = 0

def index(request):
   aj = request.headers.get('x-requested-with') == 'XMLHttpRequest'
   # print("ajax : " + str(request.headers.get('x-requested-with') == 'XMLHttpRequest'))

   temp = 'dl_images/index.html'
   msg = ""
   d = False

   if request.method == 'POST' and not aj:

      form = search_form(request.POST)

      msg = request
      if form.is_valid():
         url = form.cleaned_data['url']
         d = dl(url)
         sleep(3)
   form = search_form()

   # print(request.method)
   # print(request.POST.get('url',None))

   if aj:
      return JsonResponse({'p':process,'t':total,'s':d})

   return render(request,temp,{'form':form,'message':msg})

def set_process(i):
   global process
   process = i
   return i
def set_total(i):
   global total
   total = i
   return i

mysite/dl_images/templates/dl_images/hello.html
{{message}}

mysite/dl_images/templates/dl_images/index.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
    <head>
        <title>dl_image</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link href="{% static 'dl_images/css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="icon" type="image/svg+xml" href="{% static 'dl_images/icon/favicon.svg' %}">

    </head>
    <body>
        <div class="container">
            <div class="bg-light p-4 p-sm-5 my-4 rounded">
                <h1>dl_image</h1>
                <!-- <h2>{{message}}</h2> -->
                <h2 id="timer"></h2>
            </div>
            <form method="post" action="" class="fom-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_url" class="col-sm-4 control-label">URL:</label>
                    <div class="col-sm-8 my-1">{{form.url|add_class:'form-control'}}</div>
                    <!-- <div class="col-sm-8">{{form.message|add_class:'form-control'}}</div> -->
                    <button type="submit" class="btn btn-primary my-1" id="submit">Submit</button>
                </div>
            </form>
            <div id="progressbar">
                <!-- <div class="progress my-3" style="height:30px;">
                    <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:50%"></div>
                </div> -->
            </div>
        </div>
        <script src="{% static 'dl_images/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'dl_images/js/jquery.min.js' %}"></script>
        <script src="{% static 'dl_images/js/progress.js' %}"></script>
    </body>
</html>